# Generated by Django 5.0.7 on 2024-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
    ]
